# Mailpit Configuration for Attendance Management System

version: "3.8"

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: attendance_mailpit
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_MAX_MESSAGES: 5000
    volumes:
      - mailpit_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: attendance_postgres
    environment:
      POSTGRES_DB: attendance_management
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/sample-data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql
    restart: unless-stopped

volumes:
  mailpit_data:
  postgres_data:
